# Site settings
theme: jekyll-theme-easy-wedding
title: Aleta & Ira
email: strawberriesandoysters@gmail.com
url: https://strawberriesandoysters.github.io/ # Be sure to include http:// or https://
description: "We're getting married and can't wait to celebrate with you!"
baseurl: ""

collections:
  stories:
    sort_by: order
  banners:

sass:
  style: compressed

defaults:
  - scope:
      path: "photos/"
    values:
      image: true
  - scope:
      type: banners
    values:
      layout: banner

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - _compress_images_cache.yml
