google_analytics_id: "G-MSRQ7W5F3R"

hero_image: assets/img/backgrounds/saltwater.jpg
hero_position: center center
# mobile_hero_image: assets/img/bell.jpg
# mobile_hero_position: center center

theme:
  # text_color: '#404040'
  primary_color: '#4c6d41'
  secondary_color: '#4c6d41'
  accent_color: '#62416D'
  background_color: '#ffff'


  # Comment these out to disable
